/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "pulse": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "laratrust.permissions.index": [],
    "laratrust.permissions.create": [],
    "laratrust.permissions.store": [],
    "laratrust.permissions.edit": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.permissions.update": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.roles.index": [],
    "laratrust.roles.create": [],
    "laratrust.roles.store": [],
    "laratrust.roles.show": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.edit": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.update": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.destroy": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles-assignment.index": [],
    "laratrust.roles-assignment.edit": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "laratrust.roles-assignment.update": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "index": [],
    "store": [],
    "about": [],
    "status.index": [],
    "login": [],
    "login.submit": [],
    "forgot": [],
    "forgot.submit": [],
    "logout": [],
    "dashboard.index": [],
    "my-groups.index": [],
    "dashboard.my-groups.index": [],
    "dashboard.joined-groups.index": [],
    "dashboard.account.index": [],
    "dashboard.manage-groups.index": [],
    "dashboard.manage-groups.store": [],
    "dashboard.manage-groups.edit": [
        {
            "name": "manage_group",
            "required": true
        }
    ],
    "dashboard.manage-groups.update": [
        {
            "name": "manage_group",
            "required": true
        }
    ],
    "dashboard.manage-groups.destroy": [
        {
            "name": "manage_group",
            "required": true
        }
    ],
    "dashboard.manage-groups.users-suggestion": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard.manage-users.index": [],
    "dashboard.manage-users.store": [],
    "dashboard.manage-users.edit": [
        {
            "name": "manage_user",
            "required": true
        }
    ],
    "dashboard.manage-users.update": [
        {
            "name": "manage_user",
            "required": true
        }
    ],
    "dashboard.manage-users.destroy": [
        {
            "name": "manage_user",
            "required": true
        }
    ],
    "dashboard.system-roles-permissions.index": [],
    "dashboard.system-roles-permissions.update": [
        {
            "name": "system_roles_permission",
            "required": true
        }
    ],
    "dashboard.system-settings.index": [],
    "dashboard.system-settings.update": [
        {
            "name": "system_setting",
            "required": true
        }
    ],
    "dashboard.manage-template-tasks.edit": [
        {
            "name": "manage_template_task",
            "required": true
        }
    ],
    "dashboard.manage-template-tasks.update": [
        {
            "name": "manage_template_task",
            "required": true
        }
    ],
    "dashboard.manage-posts.index": [],
    "dashboard.manage-posts.store": [],
    "dashboard.manage-posts.update": [
        {
            "name": "manage_post",
            "required": true
        }
    ],
    "dashboard.manage-posts.destroy": [
        {
            "name": "manage_post",
            "required": true
        }
    ],
    "dashboard.manage-comments.store": [],
    "dashboard.manage-comments.destroy": [
        {
            "name": "manage_comment",
            "required": true
        }
    ],
    "dashboard.reactions.index": []
}
}
export {};
